### PR TITLE
Correct displayFn as it is a function not an array

### PR DESCRIPTION
**Pull request by SDAdham**
#### Changes
 

Fixes # (issue)

#### Type of change

`displayFn` is intended to be a function not an array and my apologize, I oversaw the `selectedDisplayText` in my last pull request.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by SDAdham** [comment]
I have tested my code. Sorry again for the last pull request.

**Comment by SDAdham** [comment]
@manishjanky can you please merge this branch and push, we are unable to release because of this repo.

**Comment by manishjanky** [comment]
@SDAdham can you please add a couple of test cases for the piece of code you added. As any new conditions etc not covered impact the code coverage. I will merge the changes as soon as you do that. I did make these changes but thats fine. Please update the pull request with test cases then i will merge.
Thanks

**Comment by SDAdham** [comment]
on it.

**Comment by SDAdham** [comment]
I had trouble running the tests on my local machine as I didn't setup chrome, I just did a small test and a push, hopefully ci can take care of the test and run it for us.

**Comment by SDAdham** [comment]
Ok, I just tested locally now and it's successful, pls let me know if there is anything I'm missing. Thx @manishjanky

**Comment by SDAdham** [comment]
Hello @manishjanky, any updates on this one?

**Comment by manishjanky** [comment]
This is published v1.5.0
Please test and let me know if you find any issues.

**Comment by SDAdham** [comment]
Thanks, working on it now.

**Comment by SDAdham** [comment]
It's working good. Thanks @manishjanky

**Pull request merged**
